/**
 * This file is autogenerated by Scaffold-ETH.
 * You should not edit it manually or your changes might be overwritten.
 */
import { GenericContractsDeclaration } from "~~/utils/scaffold-eth/contract";

const deployedContracts = {
  10143: {
    WatchHubRating: {
      address: "0xf4EC4D3f933645953eB62B8800ca3606573B0A31",
      abi: [
        {
          anonymous: false,
          inputs: [
            {
              indexed: true,
              internalType: "address",
              name: "rater",
              type: "address",
            },
            {
              indexed: true,
              internalType: "uint256",
              name: "movieId",
              type: "uint256",
            },
            {
              indexed: false,
              internalType: "uint8",
              name: "score",
              type: "uint8",
            },
            {
              indexed: false,
              internalType: "bool",
              name: "isUpdate",
              type: "bool",
            },
          ],
          name: "MovieRated",
          type: "event",
        },
        {
          inputs: [
            {
              internalType: "uint256",
              name: "movieId",
              type: "uint256",
            },
          ],
          name: "getAverageRating",
          outputs: [
            {
              internalType: "uint256",
              name: "averageScaled",
              type: "uint256",
            },
          ],
          stateMutability: "view",
          type: "function",
        },
        {
          inputs: [
            {
              internalType: "uint256",
              name: "movieId",
              type: "uint256",
            },
          ],
          name: "getMovieStats",
          outputs: [
            {
              internalType: "uint256",
              name: "totalScore",
              type: "uint256",
            },
            {
              internalType: "uint256",
              name: "ratingCount",
              type: "uint256",
            },
            {
              internalType: "uint256",
              name: "averageScaled",
              type: "uint256",
            },
          ],
          stateMutability: "view",
          type: "function",
        },
        {
          inputs: [],
          name: "getRatedMovieCount",
          outputs: [
            {
              internalType: "uint256",
              name: "",
              type: "uint256",
            },
          ],
          stateMutability: "view",
          type: "function",
        },
        {
          inputs: [],
          name: "getRatedMovieIds",
          outputs: [
            {
              internalType: "uint256[]",
              name: "",
              type: "uint256[]",
            },
          ],
          stateMutability: "view",
          type: "function",
        },
        {
          inputs: [
            {
              internalType: "uint256",
              name: "movieId",
              type: "uint256",
            },
            {
              internalType: "address",
              name: "user",
              type: "address",
            },
          ],
          name: "getUserRating",
          outputs: [
            {
              internalType: "uint8",
              name: "",
              type: "uint8",
            },
          ],
          stateMutability: "view",
          type: "function",
        },
        {
          inputs: [
            {
              internalType: "uint256",
              name: "movieId",
              type: "uint256",
            },
            {
              internalType: "address",
              name: "user",
              type: "address",
            },
          ],
          name: "hasUserRated",
          outputs: [
            {
              internalType: "bool",
              name: "",
              type: "bool",
            },
          ],
          stateMutability: "view",
          type: "function",
        },
        {
          inputs: [
            {
              internalType: "uint256",
              name: "movieId",
              type: "uint256",
            },
            {
              internalType: "uint8",
              name: "score",
              type: "uint8",
            },
          ],
          name: "rateMovie",
          outputs: [],
          stateMutability: "nonpayable",
          type: "function",
        },
      ],
      inheritedFunctions: {},
    },
  },
} as const;

export default deployedContracts satisfies GenericContractsDeclaration;
